# Generated by Django 2.1.2 on 2018-11-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181127_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='images/profile.png', upload_to='image/%Y/%m'),
        ),
    ]
