# Generated by Django 2.1.2 on 2018-12-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181127_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='static/images/profile.png', upload_to='image/%Y/%m'),
        ),
    ]
