# Generated by Django 2.1.2 on 2018-12-13 07:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0002_goods_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_auto_20181213_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trolly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='购物车添加时间')),
                ('num', models.IntegerField(verbose_name='添加数量')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='购物车商品', to='goods.Goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='购物车主人', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '购物车商品',
                'verbose_name_plural': '购物车商品',
            },
        ),
        migrations.CreateModel(
            name='UserDemand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='需求商品名字')),
                ('detail', models.CharField(max_length=200, verbose_name='详细描述')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='应征商品', to='goods.Goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='发起人', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户需求',
                'verbose_name_plural': '用户需求',
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='收藏商品', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='用户', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户收藏',
                'verbose_name_plural': '用户收藏',
            },
        ),
        migrations.CreateModel(
            name='Usermessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500, verbose_name='消息内容')),
                ('hasread', models.BooleanField(default=False, verbose_name='是否已读')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='发送时间')),
                ('fruser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='发送者', to=settings.AUTH_USER_MODEL)),
                ('touser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='接受者', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户消息',
                'verbose_name_plural': '用户消息',
            },
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('state', models.IntegerField(verbose_name='订单状态')),
                ('price', models.FloatField(default=0, verbose_name='总价')),
                ('adress', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='收货地址', to='users.Useradress')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
    ]
