# Generated by Django 2.1.2 on 2018-12-14 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20181214_0844'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='buyer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='收货人', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userorder',
            name='goods',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='购买商品', to='goods.Goods'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userorder',
            name='num',
            field=models.IntegerField(default=1, verbose_name='购买数量'),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='state',
            field=models.IntegerField(default=0, verbose_name='订单状态'),
        ),
    ]
