# Generated by Django 2.1.2 on 2018-11-26 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='商品名称')),
                ('desc', models.CharField(max_length=300, verbose_name='商品描述')),
                ('type', models.IntegerField(verbose_name='商品种类')),
                ('state', models.IntegerField(verbose_name='状态')),
                ('fromtime', models.DateTimeField(verbose_name='开始时间')),
                ('totime', models.DateTimeField(verbose_name='结束时间')),
                ('release_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('price', models.FloatField(verbose_name='价格')),
                ('location', models.CharField(max_length=100, verbose_name='地点')),
                ('image', models.ImageField(max_length=300, upload_to='goods/%Y/%M', verbose_name='封面图')),
                ('num', models.IntegerField(default=1, verbose_name='持有数量')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
    ]
